apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp1-prod
  annotations:
    argocd.argoproj.io/sync-wave: "3"

resources:
  - ../../envs/dev  # Base from dev

commonLabels:
  app.kubernetes.io/name: webapp1
  app.kubernetes.io/instance: webapp1-prod
  app.kubernetes.io/part-of: monorepo-apps
  environment: prod
  discovered-by: git-generator

namePrefix: prod-
namespace: webapp1-prod

images:
  - name: webapp1
    newTag: v1.2.3  # Versão específica para PROD

replicas:
  - name: webapp1-deployment
    count: 3  # HA em produção

patchesStrategicMerge:
  - patches/resources-prod.yaml
  - patches/env-prod.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: webapp1-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "production"