apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp1-dev
  annotations:
    argocd.argoproj.io/sync-wave: "3"

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: webapp1
  app.kubernetes.io/instance: webapp1-dev
  app.kubernetes.io/part-of: monorepo-apps
  environment: dev
  discovered-by: git-generator

namePrefix: dev-
namespace: webapp1-dev

images:
  - name: webapp1
    newTag: dev-latest

replicas:
  - name: webapp1-deployment
    count: 1

patchesStrategicMerge:
  - patches/resources-dev.yaml